### ISSUE TITLE
Feature Request: add .gitkeep to directories

### ISSUE THREAD

**Issue by damianoneill** [davestern/ansible-init#2]
Would be useful to have an option for the directories that contain no entries to generate a .gitkeep file so that the structure can be committed as an initial layout after using the playbook.  

Thanks.

**Comment by damianoneill** [comment]
Of course can be done in bash with 

````
find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;
````

Easier to configure with the playbook, especially if your adding new roles later to an existing generated playbook.

**Comment by davestern** [comment]
Interesting idea. I'd be happy to merge a PR for that.
